// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/usecase/authenticate.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/usecase/authenticate.go -destination=internal/server/storage/mocks/authenticate_user_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gophkeeper/internal/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticateUserRepository is a mock of AuthenticateUserRepository interface.
type MockAuthenticateUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticateUserRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthenticateUserRepositoryMockRecorder is the mock recorder for MockAuthenticateUserRepository.
type MockAuthenticateUserRepositoryMockRecorder struct {
	mock *MockAuthenticateUserRepository
}

// NewMockAuthenticateUserRepository creates a new mock instance.
func NewMockAuthenticateUserRepository(ctrl *gomock.Controller) *MockAuthenticateUserRepository {
	mock := &MockAuthenticateUserRepository{ctrl: ctrl}
	mock.recorder = &MockAuthenticateUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticateUserRepository) EXPECT() *MockAuthenticateUserRepositoryMockRecorder {
	return m.recorder
}

// GetUserByLoginAndPassword mocks base method.
func (m *MockAuthenticateUserRepository) GetUserByLoginAndPassword(ctx context.Context, login, passwordHash string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLoginAndPassword", ctx, login, passwordHash)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLoginAndPassword indicates an expected call of GetUserByLoginAndPassword.
func (mr *MockAuthenticateUserRepositoryMockRecorder) GetUserByLoginAndPassword(ctx, login, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLoginAndPassword", reflect.TypeOf((*MockAuthenticateUserRepository)(nil).GetUserByLoginAndPassword), ctx, login, passwordHash)
}

// MockAuthenticateUsecase is a mock of AuthenticateUsecase interface.
type MockAuthenticateUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticateUsecaseMockRecorder
	isgomock struct{}
}

// MockAuthenticateUsecaseMockRecorder is the mock recorder for MockAuthenticateUsecase.
type MockAuthenticateUsecaseMockRecorder struct {
	mock *MockAuthenticateUsecase
}

// NewMockAuthenticateUsecase creates a new mock instance.
func NewMockAuthenticateUsecase(ctrl *gomock.Controller) *MockAuthenticateUsecase {
	mock := &MockAuthenticateUsecase{ctrl: ctrl}
	mock.recorder = &MockAuthenticateUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticateUsecase) EXPECT() *MockAuthenticateUsecaseMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuthenticateUsecase) Authenticate(ctx context.Context, login, passwordHash string) (models.AuthenticateOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, login, passwordHash)
	ret0, _ := ret[0].(models.AuthenticateOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthenticateUsecaseMockRecorder) Authenticate(ctx, login, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthenticateUsecase)(nil).Authenticate), ctx, login, passwordHash)
}
