// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/server/usecase/delete_file.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeleteFileStorage is a mock of DeleteFileStorage interface.
type MockDeleteFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteFileStorageMockRecorder
}

// MockDeleteFileStorageMockRecorder is the mock recorder for MockDeleteFileStorage.
type MockDeleteFileStorageMockRecorder struct {
	mock *MockDeleteFileStorage
}

// NewMockDeleteFileStorage creates a new mock instance.
func NewMockDeleteFileStorage(ctrl *gomock.Controller) *MockDeleteFileStorage {
	mock := &MockDeleteFileStorage{ctrl: ctrl}
	mock.recorder = &MockDeleteFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteFileStorage) EXPECT() *MockDeleteFileStorageMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockDeleteFileStorage) DeleteFile(ctx context.Context, fileKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, fileKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockDeleteFileStorageMockRecorder) DeleteFile(ctx, fileKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockDeleteFileStorage)(nil).DeleteFile), ctx, fileKey)
}
