// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/server/usecase/delete_file.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "gophkeeper/internal/models"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteFileRepository is a mock of DeleteFileRepository interface.
type MockDeleteFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteFileRepositoryMockRecorder
}

// MockDeleteFileRepositoryMockRecorder is the mock recorder for MockDeleteFileRepository.
type MockDeleteFileRepositoryMockRecorder struct {
	mock *MockDeleteFileRepository
}

// NewMockDeleteFileRepository creates a new mock instance.
func NewMockDeleteFileRepository(ctrl *gomock.Controller) *MockDeleteFileRepository {
	mock := &MockDeleteFileRepository{ctrl: ctrl}
	mock.recorder = &MockDeleteFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteFileRepository) EXPECT() *MockDeleteFileRepositoryMockRecorder {
	return m.recorder
}

// GetRecordByLabel mocks base method.
func (m *MockDeleteFileRepository) GetRecordByLabel(ctx context.Context, label string, userID uuid.UUID) (*models.GetSecretOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordByLabel", ctx, label, userID)
	ret0, _ := ret[0].(*models.GetSecretOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordByLabel indicates an expected call of GetRecordByLabel.
func (mr *MockDeleteFileRepositoryMockRecorder) GetRecordByLabel(ctx, label, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordByLabel", reflect.TypeOf((*MockDeleteFileRepository)(nil).GetRecordByLabel), ctx, label, userID)
}

// DeleteRecordByLabel mocks base method.
func (m *MockDeleteFileRepository) DeleteRecordByLabel(ctx context.Context, label string, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordByLabel", ctx, label, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecordByLabel indicates an expected call of DeleteRecordByLabel.
func (mr *MockDeleteFileRepositoryMockRecorder) DeleteRecordByLabel(ctx, label, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordByLabel", reflect.TypeOf((*MockDeleteFileRepository)(nil).DeleteRecordByLabel), ctx, label, userID)
}
