// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/server/api/delete_file.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteFileUsecase is a mock of DeleteFileUsecase interface.
type MockDeleteFileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteFileUsecaseMockRecorder
}

// MockDeleteFileUsecaseMockRecorder is the mock recorder for MockDeleteFileUsecase.
type MockDeleteFileUsecaseMockRecorder struct {
	mock *MockDeleteFileUsecase
}

// NewMockDeleteFileUsecase creates a new mock instance.
func NewMockDeleteFileUsecase(ctrl *gomock.Controller) *MockDeleteFileUsecase {
	mock := &MockDeleteFileUsecase{ctrl: ctrl}
	mock.recorder = &MockDeleteFileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteFileUsecase) EXPECT() *MockDeleteFileUsecaseMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockDeleteFileUsecase) DeleteFile(ctx context.Context, label string, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, label, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockDeleteFileUsecaseMockRecorder) DeleteFile(ctx, label, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockDeleteFileUsecase)(nil).DeleteFile), ctx, label, userID)
}
