// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/usecase/download_file.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/usecase/download_file.go -destination=internal/server/storage/mocks/download_file_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gophkeeper/internal/models"
	io "io"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDownloadFileStorage is a mock of DownloadFileStorage interface.
type MockDownloadFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadFileStorageMockRecorder
	isgomock struct{}
}

// MockDownloadFileStorageMockRecorder is the mock recorder for MockDownloadFileStorage.
type MockDownloadFileStorageMockRecorder struct {
	mock *MockDownloadFileStorage
}

// NewMockDownloadFileStorage creates a new mock instance.
func NewMockDownloadFileStorage(ctrl *gomock.Controller) *MockDownloadFileStorage {
	mock := &MockDownloadFileStorage{ctrl: ctrl}
	mock.recorder = &MockDownloadFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadFileStorage) EXPECT() *MockDownloadFileStorageMockRecorder {
	return m.recorder
}

// DownloadFile mocks base method.
func (m *MockDownloadFileStorage) DownloadFile(ctx context.Context, fileKey string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, fileKey)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockDownloadFileStorageMockRecorder) DownloadFile(ctx, fileKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockDownloadFileStorage)(nil).DownloadFile), ctx, fileKey)
}

// MockDownloadFileRepository is a mock of DownloadFileRepository interface.
type MockDownloadFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadFileRepositoryMockRecorder
	isgomock struct{}
}

// MockDownloadFileRepositoryMockRecorder is the mock recorder for MockDownloadFileRepository.
type MockDownloadFileRepositoryMockRecorder struct {
	mock *MockDownloadFileRepository
}

// NewMockDownloadFileRepository creates a new mock instance.
func NewMockDownloadFileRepository(ctrl *gomock.Controller) *MockDownloadFileRepository {
	mock := &MockDownloadFileRepository{ctrl: ctrl}
	mock.recorder = &MockDownloadFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadFileRepository) EXPECT() *MockDownloadFileRepositoryMockRecorder {
	return m.recorder
}

// GetRecordByLabel mocks base method.
func (m *MockDownloadFileRepository) GetRecordByLabel(ctx context.Context, label string, userID uuid.UUID) (*models.GetSecretOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordByLabel", ctx, label, userID)
	ret0, _ := ret[0].(*models.GetSecretOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordByLabel indicates an expected call of GetRecordByLabel.
func (mr *MockDownloadFileRepositoryMockRecorder) GetRecordByLabel(ctx, label, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordByLabel", reflect.TypeOf((*MockDownloadFileRepository)(nil).GetRecordByLabel), ctx, label, userID)
}

// MockDownloadFileUsecase is a mock of DownloadFileUsecase interface.
type MockDownloadFileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadFileUsecaseMockRecorder
	isgomock struct{}
}

// MockDownloadFileUsecaseMockRecorder is the mock recorder for MockDownloadFileUsecase.
type MockDownloadFileUsecaseMockRecorder struct {
	mock *MockDownloadFileUsecase
}

// NewMockDownloadFileUsecase creates a new mock instance.
func NewMockDownloadFileUsecase(ctrl *gomock.Controller) *MockDownloadFileUsecase {
	mock := &MockDownloadFileUsecase{ctrl: ctrl}
	mock.recorder = &MockDownloadFileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadFileUsecase) EXPECT() *MockDownloadFileUsecaseMockRecorder {
	return m.recorder
}

// DownloadFile mocks base method.
func (m *MockDownloadFileUsecase) DownloadFile(ctx context.Context, label string, userID uuid.UUID) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, label, userID)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockDownloadFileUsecaseMockRecorder) DownloadFile(ctx, label, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockDownloadFileUsecase)(nil).DownloadFile), ctx, label, userID)
}
