// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/server/api/download_file.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDownloadFileUsecase is a mock of DownloadFileUsecase interface.
type MockDownloadFileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadFileUsecaseMockRecorder
}

// MockDownloadFileUsecaseMockRecorder is the mock recorder for MockDownloadFileUsecase.
type MockDownloadFileUsecaseMockRecorder struct {
	mock *MockDownloadFileUsecase
}

// NewMockDownloadFileUsecase creates a new mock instance.
func NewMockDownloadFileUsecase(ctrl *gomock.Controller) *MockDownloadFileUsecase {
	mock := &MockDownloadFileUsecase{ctrl: ctrl}
	mock.recorder = &MockDownloadFileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadFileUsecase) EXPECT() *MockDownloadFileUsecaseMockRecorder {
	return m.recorder
}

// DownloadFile mocks base method.
func (m *MockDownloadFileUsecase) DownloadFile(ctx context.Context, label string, userID uuid.UUID) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, label, userID)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockDownloadFileUsecaseMockRecorder) DownloadFile(ctx, label, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockDownloadFileUsecase)(nil).DownloadFile), ctx, label, userID)
}
