// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/server/usecase/download_file.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDownloadFileStorage is a mock of DownloadFileStorage interface.
type MockDownloadFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadFileStorageMockRecorder
}

// MockDownloadFileStorageMockRecorder is the mock recorder for MockDownloadFileStorage.
type MockDownloadFileStorageMockRecorder struct {
	mock *MockDownloadFileStorage
}

// NewMockDownloadFileStorage creates a new mock instance.
func NewMockDownloadFileStorage(ctrl *gomock.Controller) *MockDownloadFileStorage {
	mock := &MockDownloadFileStorage{ctrl: ctrl}
	mock.recorder = &MockDownloadFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadFileStorage) EXPECT() *MockDownloadFileStorageMockRecorder {
	return m.recorder
}

// DownloadFile mocks base method.
func (m *MockDownloadFileStorage) DownloadFile(ctx context.Context, fileKey string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, fileKey)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockDownloadFileStorageMockRecorder) DownloadFile(ctx, fileKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockDownloadFileStorage)(nil).DownloadFile), ctx, fileKey)
}
