// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/server/usecase/download_file.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "gophkeeper/internal/models"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDownloadFileRepository is a mock of DownloadFileRepository interface.
type MockDownloadFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadFileRepositoryMockRecorder
}

// MockDownloadFileRepositoryMockRecorder is the mock recorder for MockDownloadFileRepository.
type MockDownloadFileRepositoryMockRecorder struct {
	mock *MockDownloadFileRepository
}

// NewMockDownloadFileRepository creates a new mock instance.
func NewMockDownloadFileRepository(ctrl *gomock.Controller) *MockDownloadFileRepository {
	mock := &MockDownloadFileRepository{ctrl: ctrl}
	mock.recorder = &MockDownloadFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadFileRepository) EXPECT() *MockDownloadFileRepositoryMockRecorder {
	return m.recorder
}

// GetRecordByLabel mocks base method.
func (m *MockDownloadFileRepository) GetRecordByLabel(ctx context.Context, label string, userID uuid.UUID) (*models.GetSecretOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordByLabel", ctx, label, userID)
	ret0, _ := ret[0].(*models.GetSecretOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordByLabel indicates an expected call of GetRecordByLabel.
func (mr *MockDownloadFileRepositoryMockRecorder) GetRecordByLabel(ctx, label, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordByLabel", reflect.TypeOf((*MockDownloadFileRepository)(nil).GetRecordByLabel), ctx, label, userID)
}
