// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/usecase/get.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/usecase/get.go -destination=internal/server/storage/mocks/get_secret_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gophkeeper/internal/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGetSecretRepository is a mock of GetSecretRepository interface.
type MockGetSecretRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGetSecretRepositoryMockRecorder
	isgomock struct{}
}

// MockGetSecretRepositoryMockRecorder is the mock recorder for MockGetSecretRepository.
type MockGetSecretRepositoryMockRecorder struct {
	mock *MockGetSecretRepository
}

// NewMockGetSecretRepository creates a new mock instance.
func NewMockGetSecretRepository(ctrl *gomock.Controller) *MockGetSecretRepository {
	mock := &MockGetSecretRepository{ctrl: ctrl}
	mock.recorder = &MockGetSecretRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSecretRepository) EXPECT() *MockGetSecretRepositoryMockRecorder {
	return m.recorder
}

// GetRecordByLabel mocks base method.
func (m *MockGetSecretRepository) GetRecordByLabel(ctx context.Context, label string, userID uuid.UUID) (*models.GetSecretOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordByLabel", ctx, label, userID)
	ret0, _ := ret[0].(*models.GetSecretOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordByLabel indicates an expected call of GetRecordByLabel.
func (mr *MockGetSecretRepositoryMockRecorder) GetRecordByLabel(ctx, label, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordByLabel", reflect.TypeOf((*MockGetSecretRepository)(nil).GetRecordByLabel), ctx, label, userID)
}

// MockGetSecretUsecase is a mock of GetSecretUsecase interface.
type MockGetSecretUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetSecretUsecaseMockRecorder
	isgomock struct{}
}

// MockGetSecretUsecaseMockRecorder is the mock recorder for MockGetSecretUsecase.
type MockGetSecretUsecaseMockRecorder struct {
	mock *MockGetSecretUsecase
}

// NewMockGetSecretUsecase creates a new mock instance.
func NewMockGetSecretUsecase(ctrl *gomock.Controller) *MockGetSecretUsecase {
	mock := &MockGetSecretUsecase{ctrl: ctrl}
	mock.recorder = &MockGetSecretUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSecretUsecase) EXPECT() *MockGetSecretUsecaseMockRecorder {
	return m.recorder
}

// GetSecret mocks base method.
func (m *MockGetSecretUsecase) GetSecret(ctx context.Context, secretName string, userID uuid.UUID) (*models.GetSecretOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", ctx, secretName, userID)
	ret0, _ := ret[0].(*models.GetSecretOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockGetSecretUsecaseMockRecorder) GetSecret(ctx, secretName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockGetSecretUsecase)(nil).GetSecret), ctx, secretName, userID)
}
