// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/server/usecase (interfaces: GetSecretUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "gophkeeper/internal/models"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGetSecretUsecase is a mock of GetSecretUsecase interface.
type MockGetSecretUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetSecretUsecaseMockRecorder
}

// MockGetSecretUsecaseMockRecorder is the mock recorder for MockGetSecretUsecase.
type MockGetSecretUsecaseMockRecorder struct {
	mock *MockGetSecretUsecase
}

// NewMockGetSecretUsecase creates a new mock instance.
func NewMockGetSecretUsecase(ctrl *gomock.Controller) *MockGetSecretUsecase {
	mock := &MockGetSecretUsecase{ctrl: ctrl}
	mock.recorder = &MockGetSecretUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSecretUsecase) EXPECT() *MockGetSecretUsecaseMockRecorder {
	return m.recorder
}

// GetSecret mocks base method.
func (m *MockGetSecretUsecase) GetSecret(arg0 context.Context, arg1 string, arg2 uuid.UUID) (*models.GetSecretOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.GetSecretOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockGetSecretUsecaseMockRecorder) GetSecret(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockGetSecretUsecase)(nil).GetSecret), arg0, arg1, arg2)
}
