// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/usecase/login.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/usecase/login.go -destination=internal/server/storage/mocks/login_user_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginUserRepository is a mock of LoginUserRepository interface.
type MockLoginUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoginUserRepositoryMockRecorder
	isgomock struct{}
}

// MockLoginUserRepositoryMockRecorder is the mock recorder for MockLoginUserRepository.
type MockLoginUserRepositoryMockRecorder struct {
	mock *MockLoginUserRepository
}

// NewMockLoginUserRepository creates a new mock instance.
func NewMockLoginUserRepository(ctrl *gomock.Controller) *MockLoginUserRepository {
	mock := &MockLoginUserRepository{ctrl: ctrl}
	mock.recorder = &MockLoginUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginUserRepository) EXPECT() *MockLoginUserRepositoryMockRecorder {
	return m.recorder
}

// GetUserSalt mocks base method.
func (m *MockLoginUserRepository) GetUserSalt(ctx context.Context, login string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSalt", ctx, login)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSalt indicates an expected call of GetUserSalt.
func (mr *MockLoginUserRepositoryMockRecorder) GetUserSalt(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSalt", reflect.TypeOf((*MockLoginUserRepository)(nil).GetUserSalt), ctx, login)
}

// MockLoginUsecase is a mock of LoginUsecase interface.
type MockLoginUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockLoginUsecaseMockRecorder
	isgomock struct{}
}

// MockLoginUsecaseMockRecorder is the mock recorder for MockLoginUsecase.
type MockLoginUsecaseMockRecorder struct {
	mock *MockLoginUsecase
}

// NewMockLoginUsecase creates a new mock instance.
func NewMockLoginUsecase(ctrl *gomock.Controller) *MockLoginUsecase {
	mock := &MockLoginUsecase{ctrl: ctrl}
	mock.recorder = &MockLoginUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginUsecase) EXPECT() *MockLoginUsecaseMockRecorder {
	return m.recorder
}

// GetSalt mocks base method.
func (m *MockLoginUsecase) GetSalt(ctx context.Context, login string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalt", ctx, login)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalt indicates an expected call of GetSalt.
func (mr *MockLoginUsecaseMockRecorder) GetSalt(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalt", reflect.TypeOf((*MockLoginUsecase)(nil).GetSalt), ctx, login)
}
