// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/usecase/upload.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/usecase/upload.go -destination=internal/server/storage/mocks/record_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gophkeeper/internal/models"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRecordRepository is a mock of RecordRepository interface.
type MockRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockRecordRepositoryMockRecorder is the mock recorder for MockRecordRepository.
type MockRecordRepositoryMockRecorder struct {
	mock *MockRecordRepository
}

// NewMockRecordRepository creates a new mock instance.
func NewMockRecordRepository(ctrl *gomock.Controller) *MockRecordRepository {
	mock := &MockRecordRepository{ctrl: ctrl}
	mock.recorder = &MockRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordRepository) EXPECT() *MockRecordRepositoryMockRecorder {
	return m.recorder
}

// InsertRecord mocks base method.
func (m *MockRecordRepository) InsertRecord(ctx context.Context, id, userID uuid.UUID, label, recordType, metadata string, encryptedData []byte, fileKey, fileName string, version int, createdAt, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRecord", ctx, id, userID, label, recordType, metadata, encryptedData, fileKey, fileName, version, createdAt, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRecord indicates an expected call of InsertRecord.
func (mr *MockRecordRepositoryMockRecorder) InsertRecord(ctx, id, userID, label, recordType, metadata, encryptedData, fileKey, fileName, version, createdAt, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRecord", reflect.TypeOf((*MockRecordRepository)(nil).InsertRecord), ctx, id, userID, label, recordType, metadata, encryptedData, fileKey, fileName, version, createdAt, updatedAt)
}

// MockUploadSecretUsecase is a mock of UploadSecretUsecase interface.
type MockUploadSecretUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUploadSecretUsecaseMockRecorder
	isgomock struct{}
}

// MockUploadSecretUsecaseMockRecorder is the mock recorder for MockUploadSecretUsecase.
type MockUploadSecretUsecaseMockRecorder struct {
	mock *MockUploadSecretUsecase
}

// NewMockUploadSecretUsecase creates a new mock instance.
func NewMockUploadSecretUsecase(ctrl *gomock.Controller) *MockUploadSecretUsecase {
	mock := &MockUploadSecretUsecase{ctrl: ctrl}
	mock.recorder = &MockUploadSecretUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadSecretUsecase) EXPECT() *MockUploadSecretUsecaseMockRecorder {
	return m.recorder
}

// UploadSecret mocks base method.
func (m *MockUploadSecretUsecase) UploadSecret(ctx context.Context, in models.UploadSecretIn, userID uuid.UUID) (models.UploadSecretOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadSecret", ctx, in, userID)
	ret0, _ := ret[0].(models.UploadSecretOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadSecret indicates an expected call of UploadSecret.
func (mr *MockUploadSecretUsecaseMockRecorder) UploadSecret(ctx, in, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadSecret", reflect.TypeOf((*MockUploadSecretUsecase)(nil).UploadSecret), ctx, in, userID)
}
