// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/server/api (interfaces: StatusChecker)

// Package mocks содержит автоматически сгенерированные моки для тестирования.
// Пакет содержит моки для всех интерфейсов хранилищ и usecase,
// созданные с помощью go-mockgen для unit-тестирования.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStatusChecker is a mock of StatusChecker interface.
type MockStatusChecker struct {
	ctrl     *gomock.Controller
	recorder *MockStatusCheckerMockRecorder
}

// MockStatusCheckerMockRecorder is the mock recorder for MockStatusChecker.
type MockStatusCheckerMockRecorder struct {
	mock *MockStatusChecker
}

// NewMockStatusChecker creates a new mock instance.
func NewMockStatusChecker(ctrl *gomock.Controller) *MockStatusChecker {
	mock := &MockStatusChecker{ctrl: ctrl}
	mock.recorder = &MockStatusCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusChecker) EXPECT() *MockStatusCheckerMockRecorder {
	return m.recorder
}

// CheckStatus mocks base method.
func (m *MockStatusChecker) CheckStatus(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStatus", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckStatus indicates an expected call of CheckStatus.
func (mr *MockStatusCheckerMockRecorder) CheckStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStatus", reflect.TypeOf((*MockStatusChecker)(nil).CheckStatus), arg0)
}
