// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/usecase/update.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/usecase/update.go -destination=internal/server/storage/mocks/update_secret_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gophkeeper/internal/models"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateSecretRepository is a mock of UpdateSecretRepository interface.
type MockUpdateSecretRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateSecretRepositoryMockRecorder
	isgomock struct{}
}

// MockUpdateSecretRepositoryMockRecorder is the mock recorder for MockUpdateSecretRepository.
type MockUpdateSecretRepositoryMockRecorder struct {
	mock *MockUpdateSecretRepository
}

// NewMockUpdateSecretRepository creates a new mock instance.
func NewMockUpdateSecretRepository(ctrl *gomock.Controller) *MockUpdateSecretRepository {
	mock := &MockUpdateSecretRepository{ctrl: ctrl}
	mock.recorder = &MockUpdateSecretRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateSecretRepository) EXPECT() *MockUpdateSecretRepositoryMockRecorder {
	return m.recorder
}

// UpdateRecordByLabel mocks base method.
func (m *MockUpdateSecretRepository) UpdateRecordByLabel(ctx context.Context, label string, userID uuid.UUID, recordType, metadata string, encryptedData []byte, fileKey string, expectedVersion int, updatedAt time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecordByLabel", ctx, label, userID, recordType, metadata, encryptedData, fileKey, expectedVersion, updatedAt)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRecordByLabel indicates an expected call of UpdateRecordByLabel.
func (mr *MockUpdateSecretRepositoryMockRecorder) UpdateRecordByLabel(ctx, label, userID, recordType, metadata, encryptedData, fileKey, expectedVersion, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecordByLabel", reflect.TypeOf((*MockUpdateSecretRepository)(nil).UpdateRecordByLabel), ctx, label, userID, recordType, metadata, encryptedData, fileKey, expectedVersion, updatedAt)
}

// MockUpdateSecretUsecase is a mock of UpdateSecretUsecase interface.
type MockUpdateSecretUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateSecretUsecaseMockRecorder
	isgomock struct{}
}

// MockUpdateSecretUsecaseMockRecorder is the mock recorder for MockUpdateSecretUsecase.
type MockUpdateSecretUsecaseMockRecorder struct {
	mock *MockUpdateSecretUsecase
}

// NewMockUpdateSecretUsecase creates a new mock instance.
func NewMockUpdateSecretUsecase(ctrl *gomock.Controller) *MockUpdateSecretUsecase {
	mock := &MockUpdateSecretUsecase{ctrl: ctrl}
	mock.recorder = &MockUpdateSecretUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateSecretUsecase) EXPECT() *MockUpdateSecretUsecaseMockRecorder {
	return m.recorder
}

// UpdateSecret mocks base method.
func (m *MockUpdateSecretUsecase) UpdateSecret(ctx context.Context, in models.UpdateSecretIn, userID uuid.UUID) (models.UpdateSecretOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, in, userID)
	ret0, _ := ret[0].(models.UpdateSecretOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockUpdateSecretUsecaseMockRecorder) UpdateSecret(ctx, in, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockUpdateSecretUsecase)(nil).UpdateSecret), ctx, in, userID)
}
