// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/server/usecase/upload_file.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUploadFileStorage is a mock of UploadFileStorage interface.
type MockUploadFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUploadFileStorageMockRecorder
}

// MockUploadFileStorageMockRecorder is the mock recorder for MockUploadFileStorage.
type MockUploadFileStorageMockRecorder struct {
	mock *MockUploadFileStorage
}

// NewMockUploadFileStorage creates a new mock instance.
func NewMockUploadFileStorage(ctrl *gomock.Controller) *MockUploadFileStorage {
	mock := &MockUploadFileStorage{ctrl: ctrl}
	mock.recorder = &MockUploadFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadFileStorage) EXPECT() *MockUploadFileStorageMockRecorder {
	return m.recorder
}

// UploadFile mocks base method.
func (m *MockUploadFileStorage) UploadFile(ctx context.Context, fileKey string, reader io.Reader, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, fileKey, reader, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockUploadFileStorageMockRecorder) UploadFile(ctx, fileKey, reader, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockUploadFileStorage)(nil).UploadFile), ctx, fileKey, reader, size)
}

// DeleteFile mocks base method.
func (m *MockUploadFileStorage) DeleteFile(ctx context.Context, fileKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, fileKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockUploadFileStorageMockRecorder) DeleteFile(ctx, fileKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockUploadFileStorage)(nil).DeleteFile), ctx, fileKey)
}
