// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/usecase/upload_file.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/usecase/upload_file.go -destination=internal/server/storage/mocks/upload_file_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gophkeeper/internal/models"
	io "io"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUploadFileStorage is a mock of UploadFileStorage interface.
type MockUploadFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUploadFileStorageMockRecorder
	isgomock struct{}
}

// MockUploadFileStorageMockRecorder is the mock recorder for MockUploadFileStorage.
type MockUploadFileStorageMockRecorder struct {
	mock *MockUploadFileStorage
}

// NewMockUploadFileStorage creates a new mock instance.
func NewMockUploadFileStorage(ctrl *gomock.Controller) *MockUploadFileStorage {
	mock := &MockUploadFileStorage{ctrl: ctrl}
	mock.recorder = &MockUploadFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadFileStorage) EXPECT() *MockUploadFileStorageMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockUploadFileStorage) DeleteFile(ctx context.Context, fileKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, fileKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockUploadFileStorageMockRecorder) DeleteFile(ctx, fileKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockUploadFileStorage)(nil).DeleteFile), ctx, fileKey)
}

// UploadFile mocks base method.
func (m *MockUploadFileStorage) UploadFile(ctx context.Context, fileKey string, reader io.Reader, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, fileKey, reader, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockUploadFileStorageMockRecorder) UploadFile(ctx, fileKey, reader, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockUploadFileStorage)(nil).UploadFile), ctx, fileKey, reader, size)
}

// MockUploadFileRepository is a mock of UploadFileRepository interface.
type MockUploadFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUploadFileRepositoryMockRecorder
	isgomock struct{}
}

// MockUploadFileRepositoryMockRecorder is the mock recorder for MockUploadFileRepository.
type MockUploadFileRepositoryMockRecorder struct {
	mock *MockUploadFileRepository
}

// NewMockUploadFileRepository creates a new mock instance.
func NewMockUploadFileRepository(ctrl *gomock.Controller) *MockUploadFileRepository {
	mock := &MockUploadFileRepository{ctrl: ctrl}
	mock.recorder = &MockUploadFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadFileRepository) EXPECT() *MockUploadFileRepositoryMockRecorder {
	return m.recorder
}

// InsertRecord mocks base method.
func (m *MockUploadFileRepository) InsertRecord(ctx context.Context, id, userID uuid.UUID, label, recordType, metadata string, encryptedData []byte, fileKey, fileName string, version int, createdAt, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRecord", ctx, id, userID, label, recordType, metadata, encryptedData, fileKey, fileName, version, createdAt, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRecord indicates an expected call of InsertRecord.
func (mr *MockUploadFileRepositoryMockRecorder) InsertRecord(ctx, id, userID, label, recordType, metadata, encryptedData, fileKey, fileName, version, createdAt, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRecord", reflect.TypeOf((*MockUploadFileRepository)(nil).InsertRecord), ctx, id, userID, label, recordType, metadata, encryptedData, fileKey, fileName, version, createdAt, updatedAt)
}

// MockUploadFileUsecase is a mock of UploadFileUsecase interface.
type MockUploadFileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUploadFileUsecaseMockRecorder
	isgomock struct{}
}

// MockUploadFileUsecaseMockRecorder is the mock recorder for MockUploadFileUsecase.
type MockUploadFileUsecaseMockRecorder struct {
	mock *MockUploadFileUsecase
}

// NewMockUploadFileUsecase creates a new mock instance.
func NewMockUploadFileUsecase(ctrl *gomock.Controller) *MockUploadFileUsecase {
	mock := &MockUploadFileUsecase{ctrl: ctrl}
	mock.recorder = &MockUploadFileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadFileUsecase) EXPECT() *MockUploadFileUsecaseMockRecorder {
	return m.recorder
}

// UploadFile mocks base method.
func (m *MockUploadFileUsecase) UploadFile(ctx context.Context, label, metadata, fileName string, reader io.Reader, size int64, userID uuid.UUID) (models.UploadSecretOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, label, metadata, fileName, reader, size, userID)
	ret0, _ := ret[0].(models.UploadSecretOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockUploadFileUsecaseMockRecorder) UploadFile(ctx, label, metadata, fileName, reader, size, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockUploadFileUsecase)(nil).UploadFile), ctx, label, metadata, fileName, reader, size, userID)
}
