// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/server/api/upload_file.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	models "gophkeeper/internal/models"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUploadFileUsecase is a mock of UploadFileUsecase interface.
type MockUploadFileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUploadFileUsecaseMockRecorder
}

// MockUploadFileUsecaseMockRecorder is the mock recorder for MockUploadFileUsecase.
type MockUploadFileUsecaseMockRecorder struct {
	mock *MockUploadFileUsecase
}

// NewMockUploadFileUsecase creates a new mock instance.
func NewMockUploadFileUsecase(ctrl *gomock.Controller) *MockUploadFileUsecase {
	mock := &MockUploadFileUsecase{ctrl: ctrl}
	mock.recorder = &MockUploadFileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadFileUsecase) EXPECT() *MockUploadFileUsecaseMockRecorder {
	return m.recorder
}

// UploadFile mocks base method.
func (m *MockUploadFileUsecase) UploadFile(ctx context.Context, label, metadata string, file io.Reader, size int64, userID uuid.UUID) (models.UploadSecretOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, label, metadata, file, size, userID)
	ret0, _ := ret[0].(models.UploadSecretOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockUploadFileUsecaseMockRecorder) UploadFile(ctx, label, metadata, file, size, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockUploadFileUsecase)(nil).UploadFile), ctx, label, metadata, file, size, userID)
}
