// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/server/usecase/upload_file.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUploadFileRepository is a mock of UploadFileRepository interface.
type MockUploadFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUploadFileRepositoryMockRecorder
}

// MockUploadFileRepositoryMockRecorder is the mock recorder for MockUploadFileRepository.
type MockUploadFileRepositoryMockRecorder struct {
	mock *MockUploadFileRepository
}

// NewMockUploadFileRepository creates a new mock instance.
func NewMockUploadFileRepository(ctrl *gomock.Controller) *MockUploadFileRepository {
	mock := &MockUploadFileRepository{ctrl: ctrl}
	mock.recorder = &MockUploadFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadFileRepository) EXPECT() *MockUploadFileRepositoryMockRecorder {
	return m.recorder
}

// InsertRecord mocks base method.
func (m *MockUploadFileRepository) InsertRecord(ctx context.Context, id, userID uuid.UUID, label, recordType, metadata string, encryptedData []byte, fileKey string, version int, createdAt, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRecord", ctx, id, userID, label, recordType, metadata, encryptedData, fileKey, version, createdAt, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRecord indicates an expected call of InsertRecord.
func (mr *MockUploadFileRepositoryMockRecorder) InsertRecord(ctx, id, userID, label, recordType, metadata, encryptedData, fileKey, version, createdAt, updatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRecord", reflect.TypeOf((*MockUploadFileRepository)(nil).InsertRecord), ctx, id, userID, label, recordType, metadata, encryptedData, fileKey, version, createdAt, updatedAt)
}
