// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/usecase/register.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/usecase/register.go -destination=internal/server/storage/mocks/user_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gophkeeper/internal/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockUserRepository) Register(ctx context.Context, userID uuid.UUID, login, passwordHash, salt string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, userID, login, passwordHash, salt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserRepositoryMockRecorder) Register(ctx, userID, login, passwordHash, salt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserRepository)(nil).Register), ctx, userID, login, passwordHash, salt)
}

// MockRegisterUsecase is a mock of RegisterUsecase interface.
type MockRegisterUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterUsecaseMockRecorder
	isgomock struct{}
}

// MockRegisterUsecaseMockRecorder is the mock recorder for MockRegisterUsecase.
type MockRegisterUsecaseMockRecorder struct {
	mock *MockRegisterUsecase
}

// NewMockRegisterUsecase creates a new mock instance.
func NewMockRegisterUsecase(ctrl *gomock.Controller) *MockRegisterUsecase {
	mock := &MockRegisterUsecase{ctrl: ctrl}
	mock.recorder = &MockRegisterUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegisterUsecase) EXPECT() *MockRegisterUsecaseMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockRegisterUsecase) Register(ctx context.Context, in models.RegisterIn) (models.AuthenticateOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, in)
	ret0, _ := ret[0].(models.AuthenticateOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockRegisterUsecaseMockRecorder) Register(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockRegisterUsecase)(nil).Register), ctx, in)
}
