// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/shell/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/client/shell/interfaces.go -destination=internal/client/shell/mocks.go -package=shell
//

// Package shell is a generated GoMock package.
package shell

import (
	context "context"
	models "gophkeeper/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommandRegistry is a mock of CommandRegistry interface.
type MockCommandRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRegistryMockRecorder
	isgomock struct{}
}

// MockCommandRegistryMockRecorder is the mock recorder for MockCommandRegistry.
type MockCommandRegistryMockRecorder struct {
	mock *MockCommandRegistry
}

// NewMockCommandRegistry creates a new mock instance.
func NewMockCommandRegistry(ctrl *gomock.Controller) *MockCommandRegistry {
	mock := &MockCommandRegistry{ctrl: ctrl}
	mock.recorder = &MockCommandRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRegistry) EXPECT() *MockCommandRegistryMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCommandRegistry) Execute(ctx context.Context, commandName string, args any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, commandName, args)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCommandRegistryMockRecorder) Execute(ctx, commandName, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCommandRegistry)(nil).Execute), ctx, commandName, args)
}

// MockInputHandler is a mock of InputHandler interface.
type MockInputHandler struct {
	ctrl     *gomock.Controller
	recorder *MockInputHandlerMockRecorder
	isgomock struct{}
}

// MockInputHandlerMockRecorder is the mock recorder for MockInputHandler.
type MockInputHandlerMockRecorder struct {
	mock *MockInputHandler
}

// NewMockInputHandler creates a new mock instance.
func NewMockInputHandler(ctrl *gomock.Controller) *MockInputHandler {
	mock := &MockInputHandler{ctrl: ctrl}
	mock.recorder = &MockInputHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputHandler) EXPECT() *MockInputHandlerMockRecorder {
	return m.recorder
}

// GetCardData mocks base method.
func (m *MockInputHandler) GetCardData() (*models.CardData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardData")
	ret0, _ := ret[0].(*models.CardData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCardData indicates an expected call of GetCardData.
func (mr *MockInputHandlerMockRecorder) GetCardData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardData", reflect.TypeOf((*MockInputHandler)(nil).GetCardData))
}

// GetFileData mocks base method.
func (m *MockInputHandler) GetFileData() (*models.FileData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileData")
	ret0, _ := ret[0].(*models.FileData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileData indicates an expected call of GetFileData.
func (mr *MockInputHandlerMockRecorder) GetFileData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileData", reflect.TypeOf((*MockInputHandler)(nil).GetFileData))
}

// GetLoginPasswordData mocks base method.
func (m *MockInputHandler) GetLoginPasswordData() (*models.LoginPasswordData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginPasswordData")
	ret0, _ := ret[0].(*models.LoginPasswordData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginPasswordData indicates an expected call of GetLoginPasswordData.
func (mr *MockInputHandlerMockRecorder) GetLoginPasswordData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginPasswordData", reflect.TypeOf((*MockInputHandler)(nil).GetLoginPasswordData))
}

// GetSecretName mocks base method.
func (m *MockInputHandler) GetSecretName() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretName")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretName indicates an expected call of GetSecretName.
func (mr *MockInputHandlerMockRecorder) GetSecretName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretName", reflect.TypeOf((*MockInputHandler)(nil).GetSecretName))
}

// GetTextData mocks base method.
func (m *MockInputHandler) GetTextData() (*models.TextSecretData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextData")
	ret0, _ := ret[0].(*models.TextSecretData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTextData indicates an expected call of GetTextData.
func (mr *MockInputHandlerMockRecorder) GetTextData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextData", reflect.TypeOf((*MockInputHandler)(nil).GetTextData))
}

// GetUpdatedCardData mocks base method.
func (m *MockInputHandler) GetUpdatedCardData(name string) (*models.CardData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatedCardData", name)
	ret0, _ := ret[0].(*models.CardData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdatedCardData indicates an expected call of GetUpdatedCardData.
func (mr *MockInputHandlerMockRecorder) GetUpdatedCardData(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatedCardData", reflect.TypeOf((*MockInputHandler)(nil).GetUpdatedCardData), name)
}

// GetUpdatedFileData mocks base method.
func (m *MockInputHandler) GetUpdatedFileData(name string) (*models.FileData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatedFileData", name)
	ret0, _ := ret[0].(*models.FileData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdatedFileData indicates an expected call of GetUpdatedFileData.
func (mr *MockInputHandlerMockRecorder) GetUpdatedFileData(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatedFileData", reflect.TypeOf((*MockInputHandler)(nil).GetUpdatedFileData), name)
}

// GetUpdatedLoginPasswordData mocks base method.
func (m *MockInputHandler) GetUpdatedLoginPasswordData(name string) (*models.LoginPasswordData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatedLoginPasswordData", name)
	ret0, _ := ret[0].(*models.LoginPasswordData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdatedLoginPasswordData indicates an expected call of GetUpdatedLoginPasswordData.
func (mr *MockInputHandlerMockRecorder) GetUpdatedLoginPasswordData(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatedLoginPasswordData", reflect.TypeOf((*MockInputHandler)(nil).GetUpdatedLoginPasswordData), name)
}

// GetUpdatedTextData mocks base method.
func (m *MockInputHandler) GetUpdatedTextData(name string) (*models.TextSecretData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatedTextData", name)
	ret0, _ := ret[0].(*models.TextSecretData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdatedTextData indicates an expected call of GetUpdatedTextData.
func (mr *MockInputHandlerMockRecorder) GetUpdatedTextData(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatedTextData", reflect.TypeOf((*MockInputHandler)(nil).GetUpdatedTextData), name)
}

// GetUserChoice mocks base method.
func (m *MockInputHandler) GetUserChoice() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserChoice")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserChoice indicates an expected call of GetUserChoice.
func (mr *MockInputHandlerMockRecorder) GetUserChoice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserChoice", reflect.TypeOf((*MockInputHandler)(nil).GetUserChoice))
}

// GetUserCredentials mocks base method.
func (m *MockInputHandler) GetUserCredentials() (*models.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCredentials")
	ret0, _ := ret[0].(*models.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCredentials indicates an expected call of GetUserCredentials.
func (mr *MockInputHandlerMockRecorder) GetUserCredentials() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCredentials", reflect.TypeOf((*MockInputHandler)(nil).GetUserCredentials))
}

// PromptEnterNewData mocks base method.
func (m *MockInputHandler) PromptEnterNewData() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PromptEnterNewData")
}

// PromptEnterNewData indicates an expected call of PromptEnterNewData.
func (mr *MockInputHandlerMockRecorder) PromptEnterNewData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptEnterNewData", reflect.TypeOf((*MockInputHandler)(nil).PromptEnterNewData))
}

// MockDisplay is a mock of Display interface.
type MockDisplay struct {
	ctrl     *gomock.Controller
	recorder *MockDisplayMockRecorder
	isgomock struct{}
}

// MockDisplayMockRecorder is the mock recorder for MockDisplay.
type MockDisplayMockRecorder struct {
	mock *MockDisplay
}

// NewMockDisplay creates a new mock instance.
func NewMockDisplay(ctrl *gomock.Controller) *MockDisplay {
	mock := &MockDisplay{ctrl: ctrl}
	mock.recorder = &MockDisplayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisplay) EXPECT() *MockDisplayMockRecorder {
	return m.recorder
}

// AuthError mocks base method.
func (m *MockDisplay) AuthError() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AuthError")
}

// AuthError indicates an expected call of AuthError.
func (mr *MockDisplayMockRecorder) AuthError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthError", reflect.TypeOf((*MockDisplay)(nil).AuthError))
}

// BackNotAllowed mocks base method.
func (m *MockDisplay) BackNotAllowed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BackNotAllowed")
}

// BackNotAllowed indicates an expected call of BackNotAllowed.
func (mr *MockDisplayMockRecorder) BackNotAllowed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackNotAllowed", reflect.TypeOf((*MockDisplay)(nil).BackNotAllowed))
}

// DisplayCardData mocks base method.
func (m *MockDisplay) DisplayCardData(secret *models.CardData, metadata string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayCardData", secret, metadata)
}

// DisplayCardData indicates an expected call of DisplayCardData.
func (mr *MockDisplayMockRecorder) DisplayCardData(secret, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayCardData", reflect.TypeOf((*MockDisplay)(nil).DisplayCardData), secret, metadata)
}

// DisplayFileData mocks base method.
func (m *MockDisplay) DisplayFileData(secret *models.FileData, metadata string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayFileData", secret, metadata)
}

// DisplayFileData indicates an expected call of DisplayFileData.
func (mr *MockDisplayMockRecorder) DisplayFileData(secret, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayFileData", reflect.TypeOf((*MockDisplay)(nil).DisplayFileData), secret, metadata)
}

// DisplayLoginPassword mocks base method.
func (m *MockDisplay) DisplayLoginPassword(secret *models.LoginPasswordData, metadata string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayLoginPassword", secret, metadata)
}

// DisplayLoginPassword indicates an expected call of DisplayLoginPassword.
func (mr *MockDisplayMockRecorder) DisplayLoginPassword(secret, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayLoginPassword", reflect.TypeOf((*MockDisplay)(nil).DisplayLoginPassword), secret, metadata)
}

// DisplaySecretInfo mocks base method.
func (m *MockDisplay) DisplaySecretInfo(secretName, secretType, metadata string, version int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplaySecretInfo", secretName, secretType, metadata, version)
}

// DisplaySecretInfo indicates an expected call of DisplaySecretInfo.
func (mr *MockDisplayMockRecorder) DisplaySecretInfo(secretName, secretType, metadata, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplaySecretInfo", reflect.TypeOf((*MockDisplay)(nil).DisplaySecretInfo), secretName, secretType, metadata, version)
}

// DisplayTextSecret mocks base method.
func (m *MockDisplay) DisplayTextSecret(secret *models.TextSecretData, metadata string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayTextSecret", secret, metadata)
}

// DisplayTextSecret indicates an expected call of DisplayTextSecret.
func (mr *MockDisplayMockRecorder) DisplayTextSecret(secret, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayTextSecret", reflect.TypeOf((*MockDisplay)(nil).DisplayTextSecret), secret, metadata)
}

// DisplayVersion mocks base method.
func (m *MockDisplay) DisplayVersion(version, buildTime string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayVersion", version, buildTime)
}

// DisplayVersion indicates an expected call of DisplayVersion.
func (mr *MockDisplayMockRecorder) DisplayVersion(version, buildTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayVersion", reflect.TypeOf((*MockDisplay)(nil).DisplayVersion), version, buildTime)
}

// ErrorMsg mocks base method.
func (m *MockDisplay) ErrorMsg(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ErrorMsg", err)
}

// ErrorMsg indicates an expected call of ErrorMsg.
func (mr *MockDisplayMockRecorder) ErrorMsg(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorMsg", reflect.TypeOf((*MockDisplay)(nil).ErrorMsg), err)
}

// Goodbye mocks base method.
func (m *MockDisplay) Goodbye() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Goodbye")
}

// Goodbye indicates an expected call of Goodbye.
func (mr *MockDisplayMockRecorder) Goodbye() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Goodbye", reflect.TypeOf((*MockDisplay)(nil).Goodbye))
}

// InvalidChoice mocks base method.
func (m *MockDisplay) InvalidChoice() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidChoice")
}

// InvalidChoice indicates an expected call of InvalidChoice.
func (mr *MockDisplayMockRecorder) InvalidChoice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidChoice", reflect.TypeOf((*MockDisplay)(nil).InvalidChoice))
}

// Logout mocks base method.
func (m *MockDisplay) Logout() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Logout")
}

// Logout indicates an expected call of Logout.
func (mr *MockDisplayMockRecorder) Logout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockDisplay)(nil).Logout))
}

// MenuChoice mocks base method.
func (m *MockDisplay) MenuChoice() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MenuChoice")
}

// MenuChoice indicates an expected call of MenuChoice.
func (mr *MockDisplayMockRecorder) MenuChoice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuChoice", reflect.TypeOf((*MockDisplay)(nil).MenuChoice))
}

// MenuError mocks base method.
func (m *MockDisplay) MenuError(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MenuError", message)
}

// MenuError indicates an expected call of MenuError.
func (mr *MockDisplayMockRecorder) MenuError(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuError", reflect.TypeOf((*MockDisplay)(nil).MenuError), message)
}

// MenuItem mocks base method.
func (m *MockDisplay) MenuItem(id, title, description string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MenuItem", id, title, description)
}

// MenuItem indicates an expected call of MenuItem.
func (mr *MockDisplayMockRecorder) MenuItem(id, title, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuItem", reflect.TypeOf((*MockDisplay)(nil).MenuItem), id, title, description)
}

// MenuTitle mocks base method.
func (m *MockDisplay) MenuTitle(title string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MenuTitle", title)
}

// MenuTitle indicates an expected call of MenuTitle.
func (mr *MockDisplayMockRecorder) MenuTitle(title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuTitle", reflect.TypeOf((*MockDisplay)(nil).MenuTitle), title)
}

// ServerConnected mocks base method.
func (m *MockDisplay) ServerConnected() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServerConnected")
}

// ServerConnected indicates an expected call of ServerConnected.
func (mr *MockDisplayMockRecorder) ServerConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerConnected", reflect.TypeOf((*MockDisplay)(nil).ServerConnected))
}

// SuccessDelete mocks base method.
func (m *MockDisplay) SuccessDelete() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SuccessDelete")
}

// SuccessDelete indicates an expected call of SuccessDelete.
func (mr *MockDisplayMockRecorder) SuccessDelete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessDelete", reflect.TypeOf((*MockDisplay)(nil).SuccessDelete))
}

// SuccessDownloadFile mocks base method.
func (m *MockDisplay) SuccessDownloadFile(filePath string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SuccessDownloadFile", filePath)
}

// SuccessDownloadFile indicates an expected call of SuccessDownloadFile.
func (mr *MockDisplayMockRecorder) SuccessDownloadFile(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessDownloadFile", reflect.TypeOf((*MockDisplay)(nil).SuccessDownloadFile), filePath)
}

// SuccessGeneric mocks base method.
func (m *MockDisplay) SuccessGeneric(commandName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SuccessGeneric", commandName)
}

// SuccessGeneric indicates an expected call of SuccessGeneric.
func (mr *MockDisplayMockRecorder) SuccessGeneric(commandName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessGeneric", reflect.TypeOf((*MockDisplay)(nil).SuccessGeneric), commandName)
}

// SuccessGet mocks base method.
func (m *MockDisplay) SuccessGet() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SuccessGet")
}

// SuccessGet indicates an expected call of SuccessGet.
func (mr *MockDisplayMockRecorder) SuccessGet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessGet", reflect.TypeOf((*MockDisplay)(nil).SuccessGet))
}

// SuccessLogin mocks base method.
func (m *MockDisplay) SuccessLogin() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SuccessLogin")
}

// SuccessLogin indicates an expected call of SuccessLogin.
func (mr *MockDisplayMockRecorder) SuccessLogin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessLogin", reflect.TypeOf((*MockDisplay)(nil).SuccessLogin))
}

// SuccessRegistration mocks base method.
func (m *MockDisplay) SuccessRegistration() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SuccessRegistration")
}

// SuccessRegistration indicates an expected call of SuccessRegistration.
func (mr *MockDisplayMockRecorder) SuccessRegistration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessRegistration", reflect.TypeOf((*MockDisplay)(nil).SuccessRegistration))
}

// SuccessUpdate mocks base method.
func (m *MockDisplay) SuccessUpdate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SuccessUpdate")
}

// SuccessUpdate indicates an expected call of SuccessUpdate.
func (mr *MockDisplayMockRecorder) SuccessUpdate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessUpdate", reflect.TypeOf((*MockDisplay)(nil).SuccessUpdate))
}

// SuccessUpload mocks base method.
func (m *MockDisplay) SuccessUpload() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SuccessUpload")
}

// SuccessUpload indicates an expected call of SuccessUpload.
func (mr *MockDisplayMockRecorder) SuccessUpload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessUpload", reflect.TypeOf((*MockDisplay)(nil).SuccessUpload))
}

// SwitchToUserMenuNotice mocks base method.
func (m *MockDisplay) SwitchToUserMenuNotice() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SwitchToUserMenuNotice")
}

// SwitchToUserMenuNotice indicates an expected call of SwitchToUserMenuNotice.
func (mr *MockDisplayMockRecorder) SwitchToUserMenuNotice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchToUserMenuNotice", reflect.TypeOf((*MockDisplay)(nil).SwitchToUserMenuNotice))
}

// Welcome mocks base method.
func (m *MockDisplay) Welcome() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Welcome")
}

// Welcome indicates an expected call of Welcome.
func (mr *MockDisplayMockRecorder) Welcome() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Welcome", reflect.TypeOf((*MockDisplay)(nil).Welcome))
}
