// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/authenticate": {
            "post": {
                "description": "Проверяет хеш пароля и возвращает токены доступа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Аутентификация пользователя",
                "parameters": [
                    {
                        "description": "Данные для аутентификации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AuthenticateIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная аутентификация, возвращены токены",
                        "schema": {
                            "$ref": "#/definitions/models.AuthenticateOut"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "401": {
                        "description": "Неверные учетные данные",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    }
                }
            }
        },
        "/api/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет секрет с сервера по имени",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Удаление секрета",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя секрета для удаления",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Секрет успешно удален"
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "401": {
                        "description": "Неавторизованный доступ",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "404": {
                        "description": "Секрет не найден",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    }
                }
            }
        },
        "/api/files": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Загружает зашифрованный файл на сервер",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Загрузка файла",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Файл для загрузки",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Метка файла",
                        "name": "label",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Метаданные файла",
                        "name": "metadata",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Файл успешно загружен",
                        "schema": {
                            "$ref": "#/definitions/models.UploadSecretOut"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "401": {
                        "description": "Неавторизованный доступ",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "409": {
                        "description": "Файл с такой меткой уже существует",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    }
                }
            }
        },
        "/api/files/{label}/download": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Скачивает зашифрованный файл с сервера по метке",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Скачивание файла",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Метка файла",
                        "name": "label",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Файл успешно скачан",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "401": {
                        "description": "Неавторизованный доступ",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "404": {
                        "description": "Файл не найден",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    }
                }
            }
        },
        "/api/get": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получает зашифрованный секрет с сервера по имени",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Получение секрета",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя секрета",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Секрет успешно получен",
                        "schema": {
                            "$ref": "#/definitions/models.GetSecretOut"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "401": {
                        "description": "Неавторизованный доступ",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "404": {
                        "description": "Секрет не найден",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "Возвращает соль для хеширования пароля",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход пользователя в систему",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный вход, возвращена соль",
                        "schema": {
                            "$ref": "#/definitions/models.LoginOut"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    }
                }
            }
        },
        "/api/register": {
            "post": {
                "description": "Регистрирует нового пользователя в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная регистрация",
                        "schema": {
                            "$ref": "#/definitions/models.AuthenticateOut"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "409": {
                        "description": "Пользователь уже существует",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    }
                }
            }
        },
        "/api/update": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновляет зашифрованный секрет на сервере с проверкой версии",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Обновление секрета",
                "parameters": [
                    {
                        "description": "Данные секрета для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateSecretIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Секрет успешно обновлен",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateSecretOut"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "401": {
                        "description": "Неавторизованный доступ",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "409": {
                        "description": "Конфликт версий",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    }
                }
            }
        },
        "/api/upload": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Загружает зашифрованный секрет на сервер",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Загрузка секрета",
                "parameters": [
                    {
                        "description": "Данные секрета для загрузки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UploadSecretIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Секрет успешно загружен",
                        "schema": {
                            "$ref": "#/definitions/models.UploadSecretOut"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "401": {
                        "description": "Неавторизованный доступ",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    }
                }
            }
        },
        "/api/version": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает только версию секрета по имени",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Получение версии секрета",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя секрета",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Версия секрета",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "401": {
                        "description": "Неавторизованный доступ",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "404": {
                        "description": "Секрет не найден",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Проверяет доступность сервиса и подключение к хранилищу данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Проверка здоровья сервиса",
                "responses": {
                    "200": {
                        "description": "Сервис работает нормально"
                    },
                    "500": {
                        "description": "Сервис недоступен",
                        "schema": {
                            "$ref": "#/definitions/models.JSONError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AuthenticateIn": {
            "type": "object",
            "properties": {
                "login": {
                    "description": "Логин пользователя",
                    "type": "string",
                    "example": "user123"
                },
                "password_hash": {
                    "description": "Хеш пароля",
                    "type": "string",
                    "example": "hash123"
                }
            }
        },
        "models.AuthenticateOut": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "Токен доступа",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refresh_token": {
                    "description": "Токен обновления",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "models.GetSecretOut": {
            "type": "object",
            "properties": {
                "encrypted_data": {
                    "description": "Зашифрованные данные",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "file_key": {
                    "description": "Ключ файла (для файловых секретов)",
                    "type": "string",
                    "example": "file_key_123"
                },
                "file_name": {
                    "description": "Имя файла (для файловых секретов)",
                    "type": "string",
                    "example": "document.txt"
                },
                "id": {
                    "description": "Уникальный идентификатор секрета",
                    "type": "string",
                    "example": "uuid-123"
                },
                "label": {
                    "description": "Метка секрета",
                    "type": "string",
                    "example": "my_secret"
                },
                "metadata": {
                    "description": "Метаданные",
                    "type": "string",
                    "example": "Personal secret"
                },
                "type": {
                    "description": "Тип секрета",
                    "type": "string",
                    "example": "text"
                },
                "version": {
                    "description": "Версия секрета",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.JSONError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP код ошибки",
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "description": "Сообщение об ошибке",
                    "type": "string",
                    "example": "Error message"
                }
            }
        },
        "models.LoginIn": {
            "type": "object",
            "properties": {
                "login": {
                    "description": "Логин пользователя",
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "models.LoginOut": {
            "type": "object",
            "properties": {
                "salt": {
                    "description": "Соль для хеширования пароля",
                    "type": "string",
                    "example": "salt123"
                }
            }
        },
        "models.RegisterIn": {
            "type": "object",
            "properties": {
                "login": {
                    "description": "Логин пользователя",
                    "type": "string",
                    "example": "user123"
                },
                "password_hash": {
                    "description": "Хеш пароля",
                    "type": "string",
                    "example": "hash123"
                },
                "salt": {
                    "description": "Соль для хеширования",
                    "type": "string",
                    "example": "salt123"
                }
            }
        },
        "models.UpdateSecretIn": {
            "type": "object",
            "properties": {
                "encrypted_data": {
                    "description": "Зашифрованные данные",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "file_key": {
                    "description": "Ключ файла (для файловых секретов)",
                    "type": "string",
                    "example": "file_key_123"
                },
                "label": {
                    "description": "Метка секрета",
                    "type": "string",
                    "example": "my_secret"
                },
                "metadata": {
                    "description": "Метаданные",
                    "type": "string",
                    "example": "Personal secret"
                },
                "type": {
                    "description": "Тип секрета",
                    "type": "string",
                    "example": "text"
                },
                "version": {
                    "description": "версия, которую ожидает клиент",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.UpdateSecretOut": {
            "type": "object",
            "properties": {
                "version": {
                    "description": "Новая версия секрета",
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "models.UploadSecretIn": {
            "type": "object",
            "properties": {
                "encrypted_data": {
                    "description": "Зашифрованные данные",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "file_key": {
                    "description": "Ключ файла (для файловых секретов)",
                    "type": "string",
                    "example": "file_key_123"
                },
                "label": {
                    "description": "Метка секрета",
                    "type": "string",
                    "example": "my_secret"
                },
                "metadata": {
                    "description": "Метаданные",
                    "type": "string",
                    "example": "Personal secret"
                },
                "type": {
                    "description": "Тип секрета",
                    "type": "string",
                    "example": "text"
                }
            }
        },
        "models.UploadSecretOut": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Уникальный идентификатор секрета",
                    "type": "string",
                    "example": "uuid-123"
                },
                "version": {
                    "description": "Версия секрета",
                    "type": "integer",
                    "example": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Токен доступа в формате Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Операции аутентификации и регистрации",
            "name": "auth"
        },
        {
            "description": "Операции с секретами (текст, логины/пароли, карты)",
            "name": "secrets"
        },
        {
            "description": "Операции с файлами",
            "name": "files"
        },
        {
            "description": "Проверка состояния сервиса",
            "name": "health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GophKeeper API",
	Description:      "API для безопасного хранения секретов и файлов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
